name: Build and Push Multi-Arch Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set version tag
      id: version
      run: |
        VERSION=$(cat version.txt)
        echo "Version from file: ${VERSION}"
        echo "VERSION=${VERSION}" >> ${GITHUB_OUTPUT}

    - name: Build and push Docker image (multi-arch)
      uses: docker/build-push-action@v5
      with:
        context: docker
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/speedtest-monitor:latest
          ${{ secrets.DOCKER_USERNAME }}/speedtest-monitor:${{ steps.version.outputs.VERSION }}
